# The relative path to the flutter_tools/bin/podhelper.rb script.
# This script is used to include the necessary dependencies for Flutter.
require File.expand_path(File.join('..', '..', '..', '..', 'packages', 'flutter_tools', 'bin', 'podhelper'), __FILE__) rescue require 'podhelper'

platform :ios, '15.0'

# List of build configurations for the project.
# This ensures CocoaPods maps our flavor configurations to the correct build types (debug/release/profile).
project 'Runner', {
  'Debug' => :debug,
  'Release' => :release,
  'Profile' => :release,
  'Debug-rider' => :debug,
  'Release-rider' => :release,
  'Profile-rider' => :release,
  'Debug-manager' => :debug,
  'Release-manager' => :release,
  'Profile-manager' => :release,
}

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    
    # Ensure all targets within the Pods project also target iOS 15.0
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
